//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForexPlatformFrontEnd.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Files\\Data")]
        public string QuoteDataFolder {
            get {
                return ((string)(this["QuoteDataFolder"]));
            }
            set {
                this["QuoteDataFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Files")]
        public string FilesFolder {
            get {
                return ((string)(this["FilesFolder"]));
            }
            set {
                this["FilesFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:13123/TradingAPI")]
        public string DefaultMT4IntegrationAddress {
            get {
                return ((string)(this["DefaultMT4IntegrationAddress"]));
            }
            set {
                this["DefaultMT4IntegrationAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("net.tcp://localhost:17992/Platform/")]
        public string PlatformUriAddress {
            get {
                return ((string)(this["PlatformUriAddress"]));
            }
            set {
                this["PlatformUriAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Files\\ofxp.s3db")]
        public string PersistencePath {
            get {
                return ((string)(this["PersistencePath"]));
            }
            set {
                this["PersistencePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Files\\Experts")]
        public string ExpertsFolder {
            get {
                return ((string)(this["ExpertsFolder"]));
            }
            set {
                this["ExpertsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeveloperMode {
            get {
                return ((bool)(this["DeveloperMode"]));
            }
            set {
                this["DeveloperMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Files\\DataStore")]
        public string DataStoreFolder {
            get {
                return ((string)(this["DataStoreFolder"]));
            }
            set {
                this["DataStoreFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.openforexplatform.com/app/onlinedatasources.xml")]
        public string DataStoreOnlineSourcesXml {
            get {
                return ((string)(this["DataStoreOnlineSourcesXml"]));
            }
            set {
                this["DataStoreOnlineSourcesXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\Logs\\ForexPlatform.FrontEnd.{DateTime}.log")]
        public string TraceLogFile {
            get {
                return ((string)(this["TraceLogFile"]));
            }
            set {
                this["TraceLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MT4Adapter.dll;MBTradingAdapter.dll;FXCMAdapter.dll")]
        public string OptionalModules {
            get {
                return ((string)(this["OptionalModules"]));
            }
            set {
                this["OptionalModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\Output.Modules\\HedgeExpertModule.dll;..\\Output.Modules\\IntegralAdapter.dll;..\\" +
            "Output.Modules\\Experts.dll")]
        public string ExternalModules {
            get {
                return ((string)(this["ExternalModules"]));
            }
            set {
                this["ExternalModules"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SingleInstanceMode {
            get {
                return ((bool)(this["SingleInstanceMode"]));
            }
            set {
                this["SingleInstanceMode"] = value;
            }
        }
    }
}
